### ISSUE TITLE
Solr Fails to start missing SLF4j

### ISSUE THREAD

**Issue by rposborne** [hipsnip-cookbooks/solr#1]
2013-08-03 17:00:23.929:WARN:oejuc.AbstractLifeCycle:FAILED SolrRequestFilter: org.apache.solr.common.SolrException: Could not find necessary SLF4j logging jars. If using Jetty, the SLF4j logging jars need to go in the jetty lib/ext directory. For other containers, the corresponding directory should be used. For more information, see: http://wiki.apache.org/solr/SolrLogging
org.apache.solr.common.SolrException: Could not find necessary SLF4j logging jars. If using Jetty, the SLF4j logging jars need to go in the jetty lib/ext directory. For other containers, the corresponding directory should be used. For more information, see: http://wiki.apache.org/solr/SolrLogging

**Comment by lbdremy** [comment]
Hi man,

Thanks for the stacktrace ... ^^
I will need a bit more in order to help you!
I.e version of Solr, Jetty, the options you use when running the cookbook (a bit of code)
You have [here](https://github.com/hipsnip-cookbooks/solr/tree/master/test/cookbooks/hipsnip-solr_test/recipes) a few working recipes with this cookbook that may help you.

Cheers

**Comment by rposborne** [comment]
Here is the json hash of the vars being passed

``` ruby
      :solr => {
         :version => "4.4.0",
         :checksum => "6ae4f981a7e5e79fd5fc3675e19602f3"
        #:link => 'http://mirrors.ibiblio.org/apache/lucene/solr/4.4.0/solr-4.4.0.tgz'
      },
      :jetty => {
        :port => 8983,
        :version => '9.0.3.v20130506',
        :link => 'http://eclipse.org/downloads/download.php?file=/jetty/9.0.3.v20130506/dist/jetty-distribution-9.0.3.v20130506.tar.gz&r=1',
        :checksum => 'eff8c9c63883cae04cec82aca01640411a6f8804971932cd477be2f98f90a6c4'
      },
      :java => {  :jdk_version => 7 },
```

**Comment by rposborne** [comment]
Manually placing SLF4j files in the jetty/lib/etx files and everything starts fine.

**Comment by lbdremy** [comment]
Ok cool this [doc](http://wiki.apache.org/solr/SolrLogging) indicates that the jar files for logging are outside of the war since 4.3. In the default recipe we need to check if the version being installed is greater or equal than 4.3 and if yes copy the logging jars into jetty/lib/etx. Would you be up to send a pull a request with these changes?

**Comment by rposborne** [comment]
I could take a look but I have little experience with Chef,   so take the pull-request with a grain of salt :-)

**Comment by lbdremy** [comment]
Ok no problem, you have a good resource [here](https://github.com/hipsnip-cookbooks/cookbook-development) to help you get up to speed on cookbook development for HipSnip cookbook, it should help you. Thanks

**Comment by dcardamo** [comment]
I tried that pach.  It raised the exception in that block and put all the files in /usr/share/jetty/lib/ext/ext instead of /usr/share/jetty/lib/ext

Here is what I used that work, slightly modified from grahambates patch:

``` ruby
ruby_block 'Copy ext libs into Jetty' do
  block do
    lib_files = Dir.glob("#{node['solr']['extracted']}/example/lib/ext/*.jar")
    ext_dir = File.join(node['jetty']['home'],'/lib/ext')

    Chef::Log.info "Copying #{lib_files} into #{ext_dir}"
    FileUtils.cp_r(lib_files, ext_dir)
  end

  action :create
  notifies :restart, "service[jetty]"
end
```

**Comment by lbdremy** [comment]
Hi @dcardamo,

Yes you're right, "the library source path globbing was wrong" and @grahambates corrected it in the next commit https://github.com/hipsnip-cookbooks/solr/pull/3 5093159e5d9b141d79e958594f36ac05e111a11e. Even with this patch from @grahambates Solr 4.5.1 doesn't start, I got an error saying collection1 is not created or something, will paste the error later and push the new test that is broken. But I found a fork that seem to have encountered this issue, and fixed it, not sure yet, it's here https://github.com/cosminvoicu/cookbook-solr/commit/0a7b1cd0af2d72baad4fd9f9ab616d707897d38e . What is the version of Solr that you're installing @grahambates @dcardamo ?
