### ISSUE TITLE
Apache have cleared out previous versions from their repository and mirrors

### ISSUE THREAD

**Issue by jos3000** [hipsnip-cookbooks/solr#2]
Look at http://apache.mirrors.timporter.net/lucene/solr/
I think the correct place to link is now:
http://archive.apache.org/dist/lucene/solr

Does that look right?

**Comment by lbdremy** [comment]
Hello master @jos3000, :)

It looks absolutely right.
We need to change the current url.

**Comment by lbdremy** [comment]
Fixed by captain @motns with the commit 02c45ea65b061ec5a2579e64717d3021fa311864
